### PR TITLE
Upgrade maven-bundle-plugin to 5.1.1 to make EBR compatible with JDK-15

### PR DESCRIPTION
**Pull request by nikhilnanivadekar**
Per the issue here: https://github.com/bndtools/bnd/wiki/Changes-in-5.1.1#fixes-since-510

### CODE REVIEW

**Comment by nikhilnanivadekar** [comment]
@guw can you please take a look at the PR? Please let me know what needs to be done to make it merge-able.

**Comment by guw** [comment]
LGTM

**Comment by guw** [comment]
@nikhilnanivadekar Can you test with a SNAPSHOT build if this solves your issue? I can not switch EBR to JDK 15 fully because of #39.

**Comment by nikhilnanivadekar** [comment]
@guw do you mean by creating a SNAPSHOT version in my local, or there is a SNAPSHOT version available somewhere? I didnt see the SNAPSHOT here: https://repo.eclipse.org/content/repositories/ebr-releases/org/eclipse/ebr/ebr-maven-plugin/
Am I looking at the wrong page?

**Comment by guw** [comment]
https://repo.eclipse.org/content/repositories/ebr-snapshots/org/eclipse/ebr/ebr-maven-plugin/1.3.0-SNAPSHOT/

**Comment by nikhilnanivadekar** [comment]
Perfect thanks! Will do the upgrade and check once build passes.
I was looking at releases part instead of snapshot, my bad, sorry!

**Comment by nikhilnanivadekar** [comment]
@guw this seems to have fixed the JDK-15 builds for Eclipse Collections: https://github.com/eclipse/eclipse-collections/pull/973

**Pull request merged**
