### PR TITLE
Port to Tycho 2.0.0

### PR DESCRIPTION
**Pull request by akurtakov**
Change-Id: Ida3a732b2633a28510fd766b09b1bfb21797f1be
Signed-off-by: Alexander Kurtakov <akurtako@redhat.com>

### CODE REVIEW

**Comment by guw** [comment]
Nice! Thanks for the patch.

**Review by guw — APPROVED** [review]

**Comment by akurtakov** [comment]
So verification build succeeded. One question, will be auto used by Orbit once accepted or some additional steps are required? I ask for https://git.eclipse.org/r/c/orbit/orbit-recipes/+/169845

**Comment by akurtakov** [comment]
I propose landing this so fix for https://bugs.eclipse.org/bugs/show_bug.cgi?id=567378 is not needed again on next tycho update (if it's caused by that.

**Comment by guw** [comment]
@akurtakov Orbit consumes the SNAPSHOT versions. Thus I should get the update once https://ci.eclipse.org/ebr/job/ebr-maven-plugins/ ran.

**Pull request merged**
