### PR TITLE
Add Jzy3d version 1.0.2

### PR DESCRIPTION
**Pull request by mwebber**
I provide this PR to add recipes for **Jzy3d** `1.0.2`.
(recipes already exist for `1.0.1`; these were added in #22).

Note that upstream project did not publish source jars for `1.0.1`; but did for `1.0.2`.

### CODE REVIEW

**Comment by guw** [comment]
Thank you @mwebber! I've updated the master branch with a fix. Can you rebase to see if the PR build is fixed then?

**Comment by mwebber** [comment]
After a few iterations, the build now fails with
`Missing sources for plugins [org.jzy3d.api.ebr_1.0.1.v20180111-2022, org.jzy3d.jdt.core.ebr_1.0.1.v20180111-2022, org.jzy3d.swt.ebr_1.0.1.v20180111-2022]`

I need to work out how to exclude source for 1.0.1, and include the source for 1.0.2. I'm tempted just to delete the 1.0.1 definition, but I suppose that's not a good idea.

**Comment by guw** [comment]
You should the delete the 1.0.1 version given that 1.0.2 is an update.

**Comment by mwebber** [comment]
I deleted 1.0.1 as suggested, and everything is now building ok. Thanks.

**Pull request merged**
